### PR TITLE
Update library to support Ember Data 1.0-beta 16

### PR DESCRIPTION
**Pull request by egeriis**
Refer to Breaking Changes in changelog: https://github.com/emberjs/data/blob/master/CHANGELOG.md#breaking-changes

Tests are passing. Let me know if I missed anything.

### CODE REVIEW

**Comment by JoshSmith** [comment]
Nice! This looks good to me.

**Comment by egeriis** [comment]
Great. Where is @kurko?

**Comment by kagemusha** [comment]
+1 have been using without any problems so far

**Comment by kurko** [comment]
@egeriis hey, I am here! Took the weekend to recover from a high load of work :smile: 

This looks awesome! Merging right away!

**Comment by egeriis** [comment]
Great to hear :)

**Pull request merged**
