### PR TITLE
Upgrading to JSON API 1.0

### PR DESCRIPTION
**Pull request by eneuhauser**
This merges [PR #14](https://github.com/eneuhauser/ember-json-api/pull/14) from @barelyknown upgrading to JSON API 1.0, includes the updates from @Asgaroth upgrading ember-data, as well as some minor tweaks. I've run this within my own application and do not see any issues.

### CODE REVIEW

**Comment by jonkoops** [comment]
Nice work @eneuhauser and @barelyknown! I will probably be spending next week migrating some of our Ember apps over to JSON API v1.0. I'll make sure to use this and give it a test.

**Comment by kurko** [comment]
This a very good PR! Please test @jonkoops and let us know :smile:

**Comment by jonkoops** [comment]
I've had some time to test today, unfortunately the library we're using to create our responses has a blocking [bug](https://github.com/cerebris/jsonapi-resources/issues/296) that needs to be resolved before I can do a complete test of our app (loading associated records are broken in it). 

The pull request seems sound and I have had the ability to test parts of it since our backend is only half broken. The data seems to be coming trough fine from what I can see. Since @eneuhauser has also been running this on his application I think we can go ahead and merge this so we can move forwards on our [deprecation path](86).

**Comment by jonkoops** [comment]
The pull request is good and all the tests seem to be running fine and dandy. I am going ahead an merge this. Thanks again to @eneuhauser and @barelyknown for your awesome work.

**Comment by shicholas** [comment]
I've been following this project for a while and thanks so much to you all (developers and maintainers)!

- random developer who loves/uses your work

**Comment by barelyknown** [comment]
:+1:

**Comment by kurko** [comment]
Released 0.6.0 with this.

**Pull request merged**
