### PR TITLE
[Upgrade] Upgraded to ember-data beta.19 and ember v1.12.0

### PR DESCRIPTION
**Pull request by Asgaroth**

### CODE REVIEW

**Comment by wvteijlingen** [comment]
:+1: would be great if this could be merged in!

**Comment by SeyZ** [comment]
:+1: Needed

**Comment by kurko** [comment]
This is awesome @Asgaroth, but needs to be rebased :D

**Comment by Asgaroth** [comment]
Will work on this tonight.

**Comment by Asgaroth** [comment]
Upgraded to ember-data beta.19 and ember v1.12.0

cc: @wvteijlingen @SeyZ @kurko

**Comment by kurko** [comment]
Could you just update the README replacing 16.1 with 19? Other than that, it looks very good.

**Comment by SeyZ** [comment]
Awesome work @Asgaroth

**Comment by wvteijlingen** [comment]
Nice work, tnx! :+1:

**Comment by GlennGeelen** [comment]
Looks awesome although when I use this PR in my project I get deprecations on type.typeKey in the json-api-adaptor.js this should be type.modelName. I was that @Asgaroth already fixed this in the master branch of his fork so I was wandering if you could add this in the beta18 branch as well.

**Comment by kurko** [comment]
@GlennGeelen I don't quite understand your comment. It was changed to `modelName`, so you shouldn't be seeing `typeKey` deprecations anymore.

Merging this and if there's anything pending, we can open a new PR.

**Pull request merged**
